language: node_js
node_js:
  - "10"
cache: npm

notifications:
  email:
    recipients:
      - cdljsj@gmail.com # 设置通知邮件
    on_success: change
    on_failure: always

before_install:
  - export TZ='Asia/Shanghai' # 更改时区

install:
  - npm install -g gitbook-cli
  - gitbook install

script:
  - gitbook build

after_script:
  - cd _book
  - git init
  - git remote add origin https://${REF}
  - git add .
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
  - git push --force --quiet "https://${TOKEN}@${REF}" master:gh-pages

branches:
  only:
    - master

env:
  global:
    - REF=github.com/cdljsj/DeFi-First-Book.git # 设置 github 地址
